### ISSUE TITLE
Move to v2 addon format

### ISSUE THREAD

**Issue by pichfl** [mainmatter/ember-promise-modals#479]
- [x] Update ember-auto-import to v2 (breaking change)
- [ ] Update to v2 format (requires ember-auto-import v2)

**Comment by BlueCutOfficial** [comment]
The conversion to v2 is in progress, here is the current plan:

- [x] Step 1: release 4.10 to deprecate the behaviors that are not Embroider-compatible and document the major changes coming in v2 👉 [See the dreprecations](https://github.com/mainmatter/ember-promise-modals/blob/v4.1.0/DEPRECATIONS.md)
- [x] Step 2: implement the breaking changes that were identified in dedicated PRs to simplify the big restructuring PRs 👉 #910, #913, #915
- [ ] Step 3: restructure the v1 addon to a monorepo to separate the addon from the dummy app
- [ ] Step 4: implement the last prerequisite before starting the conversion
- [ ] Step 5: 🌟 Convert the addon 🌟
