### ISSUE TITLE
Add ability to abort modal close

### ISSUE THREAD

**Issue by kevinansfield** [mainmatter/ember-promise-modals#853]
We're currently running [a fork of ember-promise-modals](https://github.com/TryGhost/ember-promise-modals) but it looks like most of our changes are now possible using the official addon. Our one remaining custom change is the addition of a `beforeClose` modal option.

Our typical use-case for `beforeClose` is when we have modal UI that allows user input, when that modal is closed if there are unsaved changes we want to abort the close and open another modal to get confirmation.

Simplified example:
```
setupController(controller, model) {
    this.newsletterModal = this.modals.open(
        EditNewsletterModal,
        {newsletter: model},
        {beforeClose: this.confirmUnsavedChanges}
    );
}

async confirmUnsavedChanges() {
    if (!this.model.hasDirtyAttributes) { return true; }

    // result: true = close and discard, false = abort close, allow further edits and save
    this.confirmModal = this.modals.open(ConfirmUnsavedChangesModal);

    return this.confirmModal;
}
```

Does something like this sound like an appropriate addition? Is there something like this already available that I've missed?

Our implementation in the fork was very basic and can be seen in [this commit](https://github.com/TryGhost/ember-promise-modals/commit/a36814ed4a84f3c7f8f6d0def33d59f16a14c347).

**Comment by BlueCutOfficial** [comment]
Hi, thanks for opening this. 

Our team had a look at the suggestion but preferred not to implement it. Our reasoning is that preventing the modal from being closed should be managed from the modal itself, so the close action should not be called in the first place if there are validation errors and such. If it's not possible for some reason, it's still possible to extend the addon's functionalities.

We prefer to not change the addon's public API that way unless this use case comes up frequently.
